spring:
  kafka:
    bootstrap-servers: http://${KAFKA_HOST:localhost}:${KAFKA_PORT:9093}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://${MINIO_HOST:localhost}:${MYSQL_PORT:3307}/yout
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:adminadmin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: #email
    password: #password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls: true

server:
  ssl:
    key-store: classpath:certs/domain.p12
    key-store-password: 5122


minio:
  bucket:
    store: yout-back
  url: http://${MINIO_HOST:localhost}:9000
  access-key: ${MINIO_ACCESS:admin}
  secret-key: ${MINIO_SECRET:adminadmin}

logging:
  logback:
    rollingpolicy:
      max-file-size:
        5MB

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem




